name: SERVER RELEASE
on:
  push:
    branches: main
    paths: 'packages/server/**'
jobs:
  server-build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.1"
      - name: Installing Dependencies
        run: cd packages/server&&npm install 
      - name: Log in to Docker Hub #登陆docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  #docker的用户名
          password: ${{ secrets.DOCKER_PASSWORD }}	#docker的密码
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
            push: true
            tags: user/app:latest
            context: ./packages/server

   